# .streamlit/config.toml

# This command tells Streamlit to use this theme configuration.
[theme]

# This sets the default theme to be our custom dark theme.
base = "dark"
primaryColor = "#53CA97"      # Mint Green
backgroundColor = "#1B2222"  # Eerie Black
secondaryBackgroundColor = "#293434" # Darker Shade
textColor = "#F8F8F8"          # Seasalt
font = "sans serif"

[server]
# This tells Streamlit it's running in the cloud
headless = true
# This is crucial for running behind Koyeb's proxy
enableCORS = false
# The port must match the port you expose on Koyeb
port = 8000

[browser]
# Prevents the server from trying to open a browser tab
gatherUsageStats = false
