# .streamlit/config.toml

# This command tells Streamlit to use this theme.
[theme]

# The brand's primary green color for interactive elements
primaryColor = "#53CA97"  # Mint

# A very dark gray from the color system for the main background
backgroundColor = "#1B2222"  # Eerie Black

# A slightly lighter dark gray for secondary backgrounds like the sidebar
secondaryBackgroundColor = "#293434" # A secondary shade from your guide

# A light, off-white color for all text to ensure readability
textColor = "#F8F8F8"  # Seasalt

# Use the standard sans-serif font which is clean and modern
font = "sans serif"
